spring:
  mongodb:
    uri: mongodb://admin:admin@localhost:27017/offers?authSource=admin

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    mongodb:
      auto-index-creation: true
  cache:
    type: redis
    redis:
      time-to-live: PT60M


offer:
  fetcher-offer:
    scheduler:
      delay: PT3H
    http:
      client:
        config:
          connection-timeout: 1000
          port: 443
          read-timeout: 1000
          uri: https://fake-java-offers-api.onrender.com
scheduling:
  enabled: true
auth:
  jwt:
    secret: ${JWT_SECRET}
    issuer: job-offers-backend
    expiration-days: 30
logging:
  level:
    org.springframework.security: INFO