spring:
  mongodb:
    uri: mongodb://admin:admin@localhost:27017/offers?authSource=admin


offer:
  fetcher-offer:
    scheduler:
      delay: PT3H
    http:
      client:
        config:
          connection-timeout: 1000
          port: 5057
          read-timeout: 1000
          uri: http://ec2-18-194-181-208.eu-central-1.compute.amazonaws.com
scheduling:
  enabled: true