offer:
  fetcher-offer:
    scheduler:
      delay: PT1s

scheduling:
  enabled: false
spring:
  jackson:
    datatype:
      enum:
        write-enums-using-to-string: false

logging:
  level:
    org.springframework.security: TRACE