offer:
  fetcher-offer:
    scheduler:
      delay: PT1s

scheduling:
  enabled: false
spring:
  cache:
    type: none
    redis:
      time-to-live: PT10S
  jackson:
    datatype:
      enum:
        write-enums-using-to-string: false

logging:
  level:
    org.springframework.security: TRACE